# Generated by Django 5.0.2 on 2026-07-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_cabletvprovider_dataplan_electricityprovider_and_more'),
        ('transactions', '0005_alter_transaction_provider_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='api_url',
        ),
        migrations.AddField(
            model_name='provider',
            name='api_base_url',
            field=models.URLField(blank=True, help_text='Base URL for provider integration', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='api_key',
            field=models.CharField(blank=True, help_text='Secret key for authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='avg_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_healthy',
            field=models.BooleanField(default=True, help_text='Flag indicating if the provider is currently online'),
        ),
        migrations.AddField(
            model_name='provider',
            name='priority',
            field=models.IntegerField(default=1, help_text='Routing priority (lower priority is tried first)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='successful_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(help_text='e.g. RESPONSE, ERROR', max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Time taken for request in seconds')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='services.provider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_logs', to='transactions.transaction')),
            ],
            options={
                'db_table': 'provider_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
