/*
# ABKDATA Schema — Wallets and Wallet Transactions

## Overview
Creates the wallet and wallet_transactions tables, matching the Django
backend's wallet/models.py. The Django backend uses a separate Wallet model
with balance, locked_balance, currency, and virtual account fields for
automated bank funding. WalletTransaction records every credit/debit with
balance_before and balance_after for audit.

## New Tables

1. **wallets** — One wallet per user. Stores balance, locked_balance (for
   pending transactions), currency, and virtual account details for
   automated bank funding (Nigeria NUBAN).
   - `id` bigint PK autoincrement
   - `user_id` uuid FK to auth.users, UNIQUE (one wallet per user)
   - `balance` numeric(12,2) default 0
   - `locked_balance` numeric(12,2) default 0
   - `currency` varchar(3) default 'NGN'
   - `is_active` boolean default true
   - `bank_name` varchar(100) nullable (virtual account bank)
   - `account_number` varchar(30) nullable (virtual NUBAN account)
   - `account_name` varchar(150) nullable (virtual account name)
   - `created_at`, `updated_at` timestamptz

2. **wallet_transactions** — Immutable audit trail of every wallet
   credit/debit. Records balance_before and balance_after.
   - `id` bigint PK autoincrement
   - `wallet_id` bigint FK to wallets
   - `transaction_type` varchar(10) ('CREDIT' | 'DEBIT')
   - `amount` numeric(12,2)
   - `balance_before` numeric(12,2)
   - `balance_after` numeric(12,2)
   - `description` text
   - `reference` varchar(100) nullable
   - `created_at` timestamptz

## Security
- RLS enabled on both tables.
- wallets: users read/update own; staff read all + update all (for admin
  wallet adjustments).
- wallet_transactions: users read own (via wallet ownership); staff read all.
  No client INSERT/UPDATE/DELETE — entries created server-side only.

## Auto-Wallet Creation
- A trigger creates a wallet row when a profile is created (matching the
  Django post_save signal that auto-creates wallets).
*/

-- ============================================================
-- 1. WALLETS
-- ============================================================
CREATE TABLE IF NOT EXISTS wallets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  balance numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
  locked_balance numeric(12,2) NOT NULL DEFAULT 0.00 CHECK (locked_balance >= 0),
  currency varchar(3) NOT NULL DEFAULT 'NGN',
  is_active boolean NOT NULL DEFAULT true,
  bank_name varchar(100),
  account_number varchar(30),
  account_name varchar(150),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_wallets_user_active ON wallets(user_id, is_active);

-- Users can read their own wallet
DROP POLICY IF EXISTS "select_own_wallet" ON wallets;
CREATE POLICY "select_own_wallet" ON wallets FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

-- Users can update their own wallet (e.g., virtual account details set by system)
DROP POLICY IF EXISTS "update_own_wallet" ON wallets;
CREATE POLICY "update_own_wallet" ON wallets FOR UPDATE
  TO authenticated USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Staff can read all wallets
DROP POLICY IF EXISTS "staff_read_all_wallets" ON wallets;
CREATE POLICY "staff_read_all_wallets" ON wallets FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- Staff can update all wallets (admin wallet adjustments)
DROP POLICY IF EXISTS "staff_update_all_wallets" ON wallets;
CREATE POLICY "staff_update_all_wallets" ON wallets FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 2. WALLET_TRANSACTIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id bigint NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
  transaction_type varchar(10) NOT NULL CHECK (transaction_type IN ('CREDIT', 'DEBIT')),
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  balance_before numeric(12,2) NOT NULL,
  balance_after numeric(12,2) NOT NULL,
  description text NOT NULL DEFAULT '',
  reference varchar(100),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet_created ON wallet_transactions(wallet_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_type_created ON wallet_transactions(transaction_type, created_at DESC);

-- Users can read their own wallet transactions (via wallet ownership)
DROP POLICY IF EXISTS "select_own_wallet_tx" ON wallet_transactions;
CREATE POLICY "select_own_wallet_tx" ON wallet_transactions FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM wallets w WHERE w.id = wallet_id AND w.user_id = auth.uid())
  );

-- Staff can read all wallet transactions
DROP POLICY IF EXISTS "staff_read_all_wallet_tx" ON wallet_transactions;
CREATE POLICY "staff_read_all_wallet_tx" ON wallet_transactions FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- No client INSERT/UPDATE/DELETE — wallet transactions are created
-- server-side only (edge functions / RPC) to maintain audit integrity.

-- ============================================================
-- 3. AUTO-CREATE WALLET ON PROFILE CREATION
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_profile()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.wallets (user_id, balance, locked_balance, currency, is_active)
  VALUES (NEW.id, 0.00, 0.00, 'NGN', true)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_profile_created ON profiles;
CREATE TRIGGER on_profile_created
  AFTER INSERT ON profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_profile();
