/*
# ABKDATA Schema — User Sessions

## Overview
Creates the user_sessions table, matching the Django backend's
users/models.py UserSession model. This tracks active user sessions for
security (IP address, user agent, expiry). In Supabase, session management
is primarily handled by Supabase Auth, but this table provides additional
session tracking for security auditing and forced logout.

## New Tables

1. **user_sessions** — Tracks user sessions with IP, user agent, and expiry.
   - `id` bigint PK
   - `user_id` uuid FK to auth.users, DEFAULT auth.uid()
   - `session_key` varchar(255) unique
   - `ip_address` inet
   - `user_agent` text
   - `last_activity` timestamptz
   - `created_at` timestamptz
   - `expires_at` timestamptz
   - `is_active` boolean default true

## Security
- RLS enabled.
- Users can read/insert/update their own sessions.
- Staff can read all sessions (for security auditing).
*/

CREATE TABLE IF NOT EXISTS user_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  session_key varchar(255) UNIQUE NOT NULL,
  ip_address inet NOT NULL DEFAULT '0.0.0.0',
  user_agent text NOT NULL DEFAULT '',
  last_activity timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  is_active boolean NOT NULL DEFAULT true
);

ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_active ON user_sessions(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_user_sessions_session_key ON user_sessions(session_key);

-- Users can read their own sessions
DROP POLICY IF EXISTS "select_own_sessions" ON user_sessions;
CREATE POLICY "select_own_sessions" ON user_sessions FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

-- Users can insert their own sessions
DROP POLICY IF EXISTS "insert_own_sessions" ON user_sessions;
CREATE POLICY "insert_own_sessions" ON user_sessions FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

-- Users can update their own sessions (e.g., mark inactive on logout)
DROP POLICY IF EXISTS "update_own_sessions" ON user_sessions;
CREATE POLICY "update_own_sessions" ON user_sessions FOR UPDATE
  TO authenticated USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own sessions
DROP POLICY IF EXISTS "delete_own_sessions" ON user_sessions;
CREATE POLICY "delete_own_sessions" ON user_sessions FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- Staff can read all sessions (security auditing)
DROP POLICY IF EXISTS "staff_read_all_sessions" ON user_sessions;
CREATE POLICY "staff_read_all_sessions" ON user_sessions FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );
