/*
# ABKDATA Schema — Profiles, Roles, Permissions

## Overview
Creates the user-facing tables that map the Django backend's custom User model
to Supabase Auth. Also creates the RBAC tables (roles, permissions) that the
Django backend uses for authorization.

## New Tables
1. **profiles** — Maps to Django `users` table. Extends auth.users.
2. **roles** — User roles (admin, customer, agent).
3. **permissions** — System permissions.
4. **roles_permissions** — M2M between roles and permissions.

## Security
- RLS enabled on all tables.
- profiles: users CRUD own row; staff read/update all.
- roles/permissions/roles_permissions: all authenticated read; staff write.

## Auto-Profile Creation
- A trigger creates a profiles row when a user signs up via Supabase Auth.
*/

-- ============================================================
-- 1. PROFILES (must be first — other policies reference it)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name varchar(50) NOT NULL DEFAULT '',
  last_name varchar(50) NOT NULL DEFAULT '',
  email varchar(254) UNIQUE NOT NULL,
  phone varchar(20) UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  is_verified boolean NOT NULL DEFAULT false,
  is_staff boolean NOT NULL DEFAULT false,
  is_superuser boolean NOT NULL DEFAULT false,
  last_login_ip inet,
  role_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_profiles_email_active ON profiles(email, is_active);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON profiles(phone);

DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT
  TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "staff_read_all_profiles" ON profiles;
CREATE POLICY "staff_read_all_profiles" ON profiles FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_all_profiles" ON profiles;
CREATE POLICY "staff_update_all_profiles" ON profiles FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 2. ROLES
-- ============================================================
CREATE TABLE IF NOT EXISTS roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) UNIQUE NOT NULL,
  description text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Add FK now that roles exists
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'profiles_role_id_fkey' AND table_name = 'profiles'
  ) THEN
    ALTER TABLE profiles
      ADD CONSTRAINT profiles_role_id_fkey
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role_id);

DROP POLICY IF EXISTS "read_roles" ON roles;
CREATE POLICY "read_roles" ON roles FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_roles" ON roles;
CREATE POLICY "staff_insert_roles" ON roles FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_roles" ON roles;
CREATE POLICY "staff_update_roles" ON roles FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_roles" ON roles;
CREATE POLICY "staff_delete_roles" ON roles FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 3. PERMISSIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  codename varchar(100) UNIQUE NOT NULL,
  description text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_permissions" ON permissions;
CREATE POLICY "read_permissions" ON permissions FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_permissions" ON permissions;
CREATE POLICY "staff_insert_permissions" ON permissions FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_permissions" ON permissions;
CREATE POLICY "staff_update_permissions" ON permissions FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_permissions" ON permissions;
CREATE POLICY "staff_delete_permissions" ON permissions FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 4. ROLES_PERMISSIONS (M2M)
-- ============================================================
CREATE TABLE IF NOT EXISTS roles_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id bigint NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  UNIQUE (role_id, permission_id)
);

ALTER TABLE roles_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_roles_permissions" ON roles_permissions;
CREATE POLICY "read_roles_permissions" ON roles_permissions FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_roles_permissions" ON roles_permissions;
CREATE POLICY "staff_insert_roles_permissions" ON roles_permissions FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_roles_permissions" ON roles_permissions;
CREATE POLICY "staff_delete_roles_permissions" ON roles_permissions FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 5. AUTO-CREATE PROFILE ON SIGNUP
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, phone)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', NULL)
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- 6. SEED ROLES
-- ============================================================
INSERT INTO roles (name, description, is_active) VALUES
  ('admin', 'Full system access', true),
  ('customer', 'Standard customer account', true),
  ('agent', 'Agent with elevated permissions', true)
ON CONFLICT (name) DO NOTHING;
