/*
# ABKDATA Schema — Services (Providers, Catalogs, Logs, Funding)

## Overview
Creates the service-related tables matching the Django backend's
services/models.py. This includes: aggregator providers (with health
metrics and API logs), electricity providers, cable TV providers and
packages, data plans, wallet funding requests, and provider logs.

## New Tables

1. **providers** — Telecom/utility aggregator providers (e.g. the API
   services that actually fulfill airtime/data/electricity purchases).
   Includes health metrics and priority routing.
   - `id` bigint PK
   - `name` varchar(100)
   - `api_base_url` text nullable
   - `api_key` varchar(255) nullable
   - `is_active` boolean default true
   - `is_healthy` boolean default true
   - `priority` integer default 1
   - `total_requests` integer default 0
   - `successful_requests` integer default 0
   - `avg_response_time` float default 0
   - `created_at`, `updated_at` timestamptz

2. **provider_logs** — Audit log of every provider API interaction.
   - `id` bigint PK
   - `provider_id` bigint FK to providers
   - `transaction_id` uuid nullable FK to transactions
   - `log_type` varchar(20) ('RESPONSE' | 'ERROR')
   - `endpoint` varchar(255)
   - `request_data` jsonb
   - `response_data` jsonb
   - `status_code` integer nullable
   - `response_time` float
   - `error_message` text
   - `created_at` timestamptz

3. **electricity_providers** — Electricity distribution companies.
   - `id` bigint PK
   - `name` varchar(100)
   - `code` varchar(20) unique
   - `meter_types` jsonb (array of 'PREPAID' | 'POSTPAID')
   - `is_active` boolean default true

4. **cable_tv_providers** — Cable TV providers (DStv, GOtv, StarTimes).
   - `id` bigint PK
   - `name` varchar(100)
   - `code` varchar(20) unique
   - `is_active` boolean default true

5. **cable_tv_packages** — Cable TV subscription packages per provider.
   - `id` bigint PK
   - `provider_id` bigint FK to cable_tv_providers
   - `name` varchar(100)
   - `code` varchar(50)
   - `amount` numeric(10,2)
   - `is_active` boolean default true

6. **data_plans** — Data plan catalog per network.
   - `id` bigint PK
   - `network` varchar(20) ('MTN' | 'GLO' | 'AIRTEL' | '9MOBILE')
   - `name` varchar(100)
   - `code` varchar(50)
   - `data_volume` varchar(50)
   - `validity` varchar(50)
   - `amount` numeric(10,2)
   - `is_active` boolean default true

7. **wallet_fundings** — Wallet funding requests (manual bank transfer
   or card). Admin approves/rejects.
   - `id` bigint PK
   - `user_id` uuid FK to auth.users, DEFAULT auth.uid()
   - `amount` numeric(10,2)
   - `reference` varchar(100) unique
   - `status` varchar(20) default 'pending'
     ('pending' | 'success' | 'failed')
   - `created_at` timestamptz

## Security
- RLS enabled on all tables.
- Catalog tables (providers, electricity_providers, cable_tv_providers,
  cable_tv_packages, data_plans): all authenticated read; staff write.
- wallet_fundings: users insert/read own; staff read all + update all.
- provider_logs: staff read only (no client writes).

## FK Note
- transactions.provider_id is linked to providers via a deferred FK added
  here now that providers exists.
*/

-- ============================================================
-- 1. PROVIDERS (aggregators)
-- ============================================================
CREATE TABLE IF NOT EXISTS providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  api_base_url text,
  api_key varchar(255),
  is_active boolean NOT NULL DEFAULT true,
  is_healthy boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 1,
  total_requests integer NOT NULL DEFAULT 0,
  successful_requests integer NOT NULL DEFAULT 0,
  avg_response_time float NOT NULL DEFAULT 0.0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE providers ENABLE ROW LEVEL SECURITY;

-- Add FK from transactions.provider_id to providers
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'transactions_provider_id_fkey' AND table_name = 'transactions'
  ) THEN
    ALTER TABLE transactions
      ADD CONSTRAINT transactions_provider_id_fkey
      FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tx_provider ON transactions(provider_id);

DROP POLICY IF EXISTS "read_providers" ON providers;
CREATE POLICY "read_providers" ON providers FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_providers" ON providers;
CREATE POLICY "staff_insert_providers" ON providers FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_providers" ON providers;
CREATE POLICY "staff_update_providers" ON providers FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_providers" ON providers;
CREATE POLICY "staff_delete_providers" ON providers FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 2. PROVIDER_LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS provider_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  transaction_id uuid REFERENCES transactions(id) ON DELETE CASCADE,
  log_type varchar(20) NOT NULL,
  endpoint varchar(255) NOT NULL DEFAULT '',
  request_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status_code integer,
  response_time float NOT NULL DEFAULT 0.0,
  error_message text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE provider_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_provider_logs_provider_created ON provider_logs(provider_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provider_logs_tx ON provider_logs(transaction_id);

-- Staff can read provider logs (no client writes — server-side only)
DROP POLICY IF EXISTS "staff_read_provider_logs" ON provider_logs;
CREATE POLICY "staff_read_provider_logs" ON provider_logs FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 3. ELECTRICITY_PROVIDERS
-- ============================================================
CREATE TABLE IF NOT EXISTS electricity_providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  code varchar(20) UNIQUE NOT NULL,
  meter_types jsonb NOT NULL DEFAULT '["PREPAID","POSTPAID"]'::jsonb,
  is_active boolean NOT NULL DEFAULT true
);

ALTER TABLE electricity_providers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_electricity_providers" ON electricity_providers;
CREATE POLICY "read_electricity_providers" ON electricity_providers FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_electricity_providers" ON electricity_providers;
CREATE POLICY "staff_insert_electricity_providers" ON electricity_providers FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_electricity_providers" ON electricity_providers;
CREATE POLICY "staff_update_electricity_providers" ON electricity_providers FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_electricity_providers" ON electricity_providers;
CREATE POLICY "staff_delete_electricity_providers" ON electricity_providers FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 4. CABLE_TV_PROVIDERS
-- ============================================================
CREATE TABLE IF NOT EXISTS cable_tv_providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  code varchar(20) UNIQUE NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

ALTER TABLE cable_tv_providers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_cable_tv_providers" ON cable_tv_providers;
CREATE POLICY "read_cable_tv_providers" ON cable_tv_providers FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_cable_tv_providers" ON cable_tv_providers;
CREATE POLICY "staff_insert_cable_tv_providers" ON cable_tv_providers FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_cable_tv_providers" ON cable_tv_providers;
CREATE POLICY "staff_update_cable_tv_providers" ON cable_tv_providers FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_cable_tv_providers" ON cable_tv_providers;
CREATE POLICY "staff_delete_cable_tv_providers" ON cable_tv_providers FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 5. CABLE_TV_PACKAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS cable_tv_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint NOT NULL REFERENCES cable_tv_providers(id) ON DELETE CASCADE,
  name varchar(100) NOT NULL,
  code varchar(50) NOT NULL,
  amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (provider_id, code)
);

ALTER TABLE cable_tv_packages ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_cable_packages_provider ON cable_tv_packages(provider_id);

DROP POLICY IF EXISTS "read_cable_tv_packages" ON cable_tv_packages;
CREATE POLICY "read_cable_tv_packages" ON cable_tv_packages FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_cable_tv_packages" ON cable_tv_packages;
CREATE POLICY "staff_insert_cable_tv_packages" ON cable_tv_packages FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_cable_tv_packages" ON cable_tv_packages;
CREATE POLICY "staff_update_cable_tv_packages" ON cable_tv_packages FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_cable_tv_packages" ON cable_tv_packages;
CREATE POLICY "staff_delete_cable_tv_packages" ON cable_tv_packages FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 6. DATA_PLANS
-- ============================================================
CREATE TABLE IF NOT EXISTS data_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  network varchar(20) NOT NULL CHECK (network IN ('MTN', 'GLO', 'AIRTEL', '9MOBILE')),
  name varchar(100) NOT NULL,
  code varchar(50) NOT NULL,
  data_volume varchar(50) NOT NULL DEFAULT '',
  validity varchar(50) NOT NULL DEFAULT '',
  amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (network, code)
);

ALTER TABLE data_plans ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_data_plans_network ON data_plans(network, is_active);

DROP POLICY IF EXISTS "read_data_plans" ON data_plans;
CREATE POLICY "read_data_plans" ON data_plans FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "staff_insert_data_plans" ON data_plans;
CREATE POLICY "staff_insert_data_plans" ON data_plans FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_update_data_plans" ON data_plans;
CREATE POLICY "staff_update_data_plans" ON data_plans FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

DROP POLICY IF EXISTS "staff_delete_data_plans" ON data_plans;
CREATE POLICY "staff_delete_data_plans" ON data_plans FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- ============================================================
-- 7. WALLET_FUNDINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS wallet_fundings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric(10,2) NOT NULL CHECK (amount > 0),
  reference varchar(100) UNIQUE NOT NULL DEFAULT ('FUND-' || upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 12))),
  status varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'success', 'failed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE wallet_fundings ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_wallet_fundings_user ON wallet_fundings(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_fundings_status ON wallet_fundings(status);

-- Users can insert and read their own funding requests
DROP POLICY IF EXISTS "select_own_fundings" ON wallet_fundings;
CREATE POLICY "select_own_fundings" ON wallet_fundings FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_fundings" ON wallet_fundings;
CREATE POLICY "insert_own_fundings" ON wallet_fundings FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

-- Staff can read all funding requests
DROP POLICY IF EXISTS "staff_read_all_fundings" ON wallet_fundings;
CREATE POLICY "staff_read_all_fundings" ON wallet_fundings FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );

-- Staff can update funding status (approve/reject)
DROP POLICY IF EXISTS "staff_update_fundings" ON wallet_fundings;
CREATE POLICY "staff_update_fundings" ON wallet_fundings FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_staff = true)
  );
