# Generated by Django 5.0.2 on 2026-06-27 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
