# Generated by Django 5.0.2 on 2026-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_provider_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
