# Generated by Django 5.0.2 on 2026-07-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
