# Generated by Django 5.0.2 on 2026-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_pin_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
