# Generated by Django 5.0.2 on 2026-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(blank=True, help_text='Constructed virtual account name (e.g. VTU APP - JOHN DOE)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, help_text='Unique NUBAN account number allocated to this user', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the assigned virtual bank (e.g., Wema Bank)', max_length=100, null=True),
        ),
    ]
